[project]
name = "cli-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "textual>=3.0.1",
    "textual-dev>=1.7.0",
    "websocket-client>=1.8.0",
]
