# Generated by Django 5.1.4 on 2025-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('player_1_id', models.CharField(max_length=100, null=True)),
                ('player_2_id', models.CharField(max_length=100, null=True)),
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('player_1_paddle_y', models.IntegerField(default=250)),
                ('player_2_paddle_y', models.IntegerField(default=250)),
                ('ball_x', models.IntegerField(default=400)),
                ('ball_y', models.IntegerField(default=300)),
                ('ball_dx', models.IntegerField(default=5)),
                ('ball_dy', models.IntegerField(default=5)),
                ('canvas_width', models.IntegerField(default=800)),
                ('canvas_height', models.IntegerField(default=600)),
                ('is_paused', models.BooleanField(default=True)),
                ('player_1_moving_up', models.BooleanField(default=False)),
                ('player_1_moving_down', models.BooleanField(default=False)),
                ('player_2_moving_up', models.BooleanField(default=False)),
                ('player_2_moving_down', models.BooleanField(default=False)),
            ],
        ),
    ]
